In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])

In [4]:
print("1D array:")
print("Shape:", a.shape)
print("Size:", a.size)
print("Dimension:", a.ndim)
print("Length:", len(a))

1D array:
Shape: (5,)
Size: 5
Dimension: 1
Length: 5


In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [6]:
print("\n2D array:")
print("Shape:", b.shape)
print("Size:", b.size)
print("Dimension:", b.ndim)
print("Length:", len(b))


2D array:
Shape: (2, 3)
Size: 6
Dimension: 2
Length: 2


In [7]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [8]:
print("\n3D array:")
print("Shape:", c.shape)
print("Size:", c.size)
print("Dimension:", c.ndim)
print("Length:", len(c))


3D array:
Shape: (2, 2, 3)
Size: 12
Dimension: 3
Length: 2


In [10]:
arr1 = np.arange(0, 10, 2)
print("arange:", arr1)

rand_int = np.random.randint(1, 100, size=5)
print("random.randint:", rand_int)

rand_arr = np.random.rand(3, 2)
print("random.rand:", rand_arr)

lin_space = np.linspace(0, 5, 10)
print("linspace:", lin_space)

ones_arr = np.ones((2, 3))
print("ones:", ones_arr)

zeros_arr = np.zeros((3, 2))
print("zeros:", zeros_arr)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal_elements = np.diag(arr)
print("diag:", diagonal_elements)

arr = np.array([[1, 2], [3, 4]])
print("sum:", np.sum(arr))

arr = np.array([3, 1, 5, 2, 8])
print("min:", np.min(arr))

print("max:", np.max(arr))

print("mean:", np.mean(arr))

arange: [0 2 4 6 8]
random.randint: [ 2 77 91 38 58]
random.rand: [[0.13549137 0.6863065 ]
 [0.09829019 0.29389136]
 [0.79651286 0.30243085]]
linspace: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
ones: [[1. 1. 1.]
 [1. 1. 1.]]
zeros: [[0. 0.]
 [0. 0.]
 [0. 0.]]
diag: [1 5 9]
sum: 10
min: 1
max: 8
mean: 3.8


In [11]:
arr = np.array([3, 1, 5, 2, 8])
print("min:", np.min(arr))

print("max:", np.max(arr))

print("mean:", np.mean(arr))



import numpy as np

# Generate random marks for 50 students (assuming there are 50 students)
num_students = 50
student_marks = np.random.randint(0, 101, size=num_students)

# Count the number of students who passed
passed_students_count = np.sum(student_marks >= 30)

# Filter out the marks of failed students
failed_students_marks = student_marks[student_marks < 30]

print("Number of students passed:", passed_students_count)
print("Marks of failed students:", failed_students_marks)






import numpy as np
rand_arr = np.random.randint(1, 51, size=(2, 5))
print(rand_arr)

min: 1
max: 8
mean: 3.8
Number of students passed: 35
Marks of failed students: [ 9 19 20 16 10 16 24 22  5 17  9  9  4 11 12]
[[13  5 29 12 27]
 [34 48 19  3  4]]


In [13]:
arr = np.array([3, 1, 5, 2, 8])
print("min:", np.min(arr))

print("max:", np.max(arr))

print("mean:", np.mean(arr))



import numpy as np

num_students = 50
student_marks = np.random.randint(0, 101, size=num_students)

passed_students_count = np.sum(student_marks >= 30)

failed_students_marks = student_marks[student_marks < 30]

print("Number of students passed:", passed_students_count)
print("Marks of failed students:", failed_students_marks)


min: 1
max: 8
mean: 3.8
Number of students passed: 31
Marks of failed students: [27  6  6 11 27 10 17 28 25  7 11 10  8  4 24 23 11 14 14]


In [14]:
import numpy as np
rand_arr = np.random.randint(1, 51, size=(2, 5))
print(rand_arr)

[[25  1  5  4  6]
 [14 38  4 39  5]]


In [15]:
import numpy as np

odd_numbers = np.arange(-29, 11, 2)
print("Array of odd numbers between -30 and 10:", odd_numbers)

Array of odd numbers between -30 and 10: [-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]
